### ISSUE TITLE
ENH: Selenium page actions improvement

### ISSUE THREAD

**Issue by obannak** [pyqa/imgqa#1]
**Is your feature request related to a problem? Please describe.**

- [x] Documentation to be improved

- [x] Sleep to be removed

- [x] Few WIP methods are to be closed

- [x] Coding Standards to be improved

- [x] Restructure or beautify module with decorators

- [x] Add up Logging Feature for the necessary set of actions

**Comment by surevs** [comment]
1. decorator for page wait has been implemented in place
2. Documentation is underway
3. Coding standards are underway - all possible flake8 and pep8 errors have been looked in to resolve
4. Restructuring is in progress

**Comment by surevs** [comment]
@obannak Thanks a ton! for your commits to `UI` Module.
