### ISSUE TITLE
Fix the Errors on Methods in Browser Actions

### ISSUE THREAD

**Issue by surevs** [pyqa/imgqa#26]
**Describe the bug**
Browser Actions Method to be corrected/updated 

**Methods list**

- [x] get_current_url
- [x] switch_to_alert
- [x] clear_text

**Expected behavior**
Methods to work while test is happening

**Screenshots**
NA
**Desktop (please complete the following information):**
 - Across OS
 - All Browser [e.g. chrome, safari]
 - Version [e.g. 0.3.0]

**Comment by surevs** [comment]
I assume, the work around this is complete, could you please close this ticket @gnana03 in case we are done

**Comment by gnana03** [comment]
Moved to done. Thank you!
