### ISSUE TITLE
ENH - Comparison module

### ISSUE THREAD

**Issue by Abhimaniu** [pyqa/imgqa#3]
**Is your feature request related to a problem? Please describe.**
Need to create a comparison module which supports various kinds of comparisons 

- [ ] PDF

- [ ] JSON

- [ ] Excel/CSV

- [ ] Need to Integrate Image comparison utility as well into this module

**Describe the solution you'd like**

- [ ] Method to accept two entities and compare them in an automated way

- [ ] Use the extension of file to automatically ensure that it is a supported format

- [ ] Basic checks which are needed to be checked for Excel/CSV
- File type
- Number of Rows
- Number of Columns
- Compare Column Headers of both files
- Perform a quick rearrangement of data dimensions on fly
- Compare it row wise and let the difference details be captured as part of log/result/traceback 

- [ ] Basic checks which are needed to be checked for PDFs
- File type
- Number of pages
- Compare the pdfs(text only) and let the difference details be detailed as part of an image file like png.

- [ ] Basic checks which are needed to be checked for json
- File type
- Structure of json objects.
- JSON objects are sorted.
- Compare the json objects and let the difference details be captured as part of log/result/traceback.

**Comment by surevs** [comment]
Hi @Abhimaniu , please fix the following:
- [ ] PEP8 and flake8 errors coming up on comparison utility module/file.
- [ ] Remove the commented out text from methods
- [ ] Provide a valid doc strings for methods with a clear description on how params are being used.
