### ISSUE TITLE
MAINT: Repository Maintenance activities

### ISSUE THREAD

**Issue by Abhimaniu** [pyqa/imgqa#4]
- [x] Setup Travis CI for Python 2.7 + and python 3+

- [x] Setup Automated Build and Release Mechanism for Docker 

- [x] Setup PYPA access to enable binary and source distribution factors

- [x] Update ReadMe to enable proper linking of activities

**Comment by surevs** [comment]
1. Updated the TRAVIS CI to  lint the right files.
2. Restructuring the files and folders as per standard PyPi rules and analysing to come up with an approach of automated build for PyPi.
3. Automated Build Mechanism has been setup for docker file - glowing-vein. It basically uses the automated docker hub build mechanism , as soon as a change is committed to github, builds are triggered.

**Comment by surevs** [comment]
PYPI push is successful and will continue manually for now until v1 is in place. 
ReadMe shall be replaced with `gh-pages` post v1
